# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - os-portal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          cd ./default-assets-package
          npm install
          npm run build
          cd ..
          npm run test --if-present

      - name: zip application folders
        run: |
          echo $PWD
          ls -lah
          cd ..
          echo $PWD
          ls -lah
          tar -czf output.tar.gz ./opensource-management-portal
          ls -lah
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: /home/runner/work/opensource-management-portal/output.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          
      - name: Unpack tar
        run: |
          tar -xf output.tar.gz
          ls -lah
          mkdir /app
          cd opensource-management-portal
          ls -lah
          cp -R dist /app/dist
          cp -R default-assets-package /app/default-assets-package
          cp -R node-modules /app/node-modules
          cd /app
          ls -lah

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'os-portal'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B506880B08E44393A4AD2D077960733D }}
          package: ./dist ./default-assets-package ./node-modules
