name: NIH GHMP Container (Prod) - Build & Register

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.PROD_REGISTRY_SERVER }}
        username: ${{ secrets.PROD_REGISTRY_USER }}
        password: ${{ secrets.PROD_REGISTRY_PASS }}
    - run: |
        docker build . -t ${{ secrets.PROD_REGISTRY_SERVER }}/portal
        docker push ${{ secrets.PROD_REGISTRY_SERVER }}/portal
