name: Generate and env-orgs.json file and upload to Azure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     
     - name: echo
       run: |
         ls -lah
         
     - name: auth GH CLI for enterprise:read
       run: |
         gh auth login --with-token 
       env: 
         GH_TOKEN: ${{ secrets.ENT_READ_PAT }}
         
     - name: get orgs from graphql
       run: |
         gh api graphql -f ent=ASampleEnterprise -f query='query($ent: String!) {
          enterprise(slug: $ent) {
            organizations(first: 100) {
              nodes {
                description
                databaseId
                id
                name
              }
            }
          }
         }' >> raw.json
         cat raw.json
