name: Update organizationsettings table

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     - uses: ruby/setup-ruby@v1.127.0
       with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
     
     - name: update ruby reqs
       run: |
        gem install jwt
        
     - name: run jwt generator
       run: |
         ruby .github/scripts/jwt.rb >> token
         ls -lah
       
       env:
         PEM: ${{ secrets.APP_PEM}}
         
     - name: run gh api cli to getch app data
       run: |
         gh api \
          -H "Authorization: Bearer $(cat token)" \
          -H "Accept: application/vnd.github+json" \
          /app/installations | jq >> app_output.json
          
     - name: run powershell script to build sql
       run: | 
          .github/scripts/Create-PSQLUpdate.ps1
       shell: pwsh
          
       env:
        PAT: ${{ secrets.ENT_READ_PAT }}
        
     - name: output sql
       run: |
        ls -lah
        cat ./app_output.json
        cat ./update.sql
        
