name: Update organizationsettings table

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     - uses: ruby/setup-ruby@v1.127.0
       with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
     
     - name: update ruby reqs
       run: |
        gem install jwt
        
     - name: my-app-install token
       id: os-portal
       uses: getsentry/action-github-app-token@v1
       with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PEM }}
        
     - name: run gh cli to get app install info
       run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /app/installations | jq >> app_output.json
       env:
         GITHUB_TOKEN: ${{ steps.os-portal.outputs.token }}
        

     - name: run powershell script to build sql
       run: | 
          .github/scripts/Create-PSQLUpdate.ps1
       shell: pwsh
          
       env:
        PAT: ${{ secrets.ENT_READ_PAT }}
        
     - name: output sql
       run: |
        ls -lah
        cat ./app_output.json
        cat ./update.sql
        
